services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    restart: unless-stopped
    ports:
      - "${PORT}:3000"
    environment:
      PORT: "${PORT}"
      BASE_URL: "${BASE_URL}"
      ADDON_PASSWORD: "${ADDON_PASSWORD}"
      SECRET_KEY: "${SECRET_KEY}"
      DATABASE_URI: "${DATABASE_URI}"
      AIOSTREAMS_AUTH: "${AIOSTREAMS_AUTH}"
      ANIME_DB_LEVEL_OF_DETAIL: "${ANIME_DB_LEVEL_OF_DETAIL}"
      ADDON_PROXY: "${ADDON_PROXY}"
      ADDON_PROXY_CONFIG: "${ADDON_PROXY_CONFIG}"
      WHITELISTED_SEL_URLS: "${WHITELISTED_SEL_URLS}"
      WHITELISTED_REGEX_PATTERNS_URLS: "${WHITELISTED_REGEX_PATTERNS_URLS}"
      TEMPLATE_URLS: "${TEMPLATE_URLS}"
      COMET_URL: "${COMET_URL}"
      MEDIAFUSION_URL: "${MEDIAFUSION_URL}"
      JACKETTIO_URL: "${JACKETTIO_URL}"
      STREMTHRU_STORE_URL: "${STREMTHRU_STORE_URL}"
      METEOR_URL: "${METEOR_URL}"
    depends_on:
      - warproxy

  warproxy:
    image: ghcr.io/kingcc/warproxy:latest
    restart: unless-stopped